In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4],np.int8)
# by using int8 we specify that integer value vil be less than2^7
arr

array([1, 2, 3, 4], dtype=int8)

In [4]:
print(type(arr))
arr.ndim

a = np.arange(1,7)
ab = a.reshape(-1,3,2)
ab

<class 'numpy.ndarray'>


array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
arr2 = np.array([[1,2,3,4]],np.int8)
# arr is a 2d array

In [6]:
arr2[0,2]

3

In [7]:
arr2.dtype

dtype('int8')

In [8]:
arr2.shape

(1, 4)

In [9]:
arr2[0][1] = 45
arr2

array([[ 1, 45,  3,  4]], dtype=int8)

# Array creation: Convertion from other python structures

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.shape 

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

# intrinsic numpy array creation object

In [14]:
zeros= np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.dtype

dtype('float64')

In [16]:
zeros.shape

(2, 5)

In [17]:
a = 1
b = 0
try:
    c= a/b
except Exception as e:
    print(e)

division by zero


In [18]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr  = np.array([[1,2,3,4],[5,6,7,8]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [51]:
l =["a" ,"b" ,"c" ,"d"]
arr = np.random.choice(l,20)
arr

array(['a', 'd', 'b', 'b', 'c', 'a', 'b', 'c', 'a', 'c', 'a', 'c', 'd',
       'd', 'b', 'b', 'a', 'd', 'b', 'c'], dtype='<U1')

In [49]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
emp = np.empty((3,3))
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
b = a.reshape(3,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b.sum(axis=1)

array([ 6, 22, 38])

In [27]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [28]:
transpose = b.T
transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
b.flat

In [30]:
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
b.ndim

2

In [32]:
b.size

12

In [33]:
b.nbytes

48

In [34]:
new = np.array([1,2,3,22,6,9,12])


In [35]:
new.argmax()

3

In [36]:
new.argmin()

0

In [37]:
new.argsort()

array([0, 1, 2, 4, 5, 6, 3], dtype=int64)

In [38]:
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b.argmax()

11

In [40]:
b.argmax(axis=1)

array([3, 3, 3], dtype=int64)

In [41]:
b.argsort()
# here it will be sorted because earlier we used the range function

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

# matrice operation

In [42]:
c = np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23]])
c

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
c+b


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [44]:
d = c*b
d

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [45]:
np.where(d>100)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [46]:
np.count_nonzero(d)

11

In [57]:
np.random.binomial(2,0.5 , (2,4))

array([[1, 1, 1, 2],
       [1, 2, 1, 0]])

In [60]:
np.random.uniform(90,100,(2,3))

array([[91.4486004 , 93.46213295, 96.31769792],
       [92.57442959, 99.29231177, 97.6016112 ]])

In [74]:
a = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(a)
x , y , z = np.split(arr, [1,3])
print(x)

[[1 2 3]]


In [75]:
print(y)

[[4 5 6]
 [7 8 9]]


In [76]:
print(z)

[[10 11 12]]
