In [1]:
from sklearn import svm , datasets
iris = datasets.load_iris()


In [2]:
import pandas as pd
df = pd.DataFrame(iris.data , columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
47                4.6               3.2                1.4               0.2  \
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [3]:
from sklearn.model_selection import train_test_split
X_train ,X_test , y_train , y_test = train_test_split(iris.data , iris.target , test_size=0.3)

In [4]:
model = svm.SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

K fold cross validation


In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
cross_val_score(svm.SVC(kernel='linear' , C=10 , gamma='auto') , iris.data , iris.target , cv=5)
# svm.SVC(kernel='linear' , C=10 , gamma='auto' these are tweakable parameters

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [7]:
cross_val_score(svm.SVC(kernel='rbf' , C=10 , gamma='auto') , iris.data , iris.target , cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score(svm.SVC(kernel='rbf' , C=20 , gamma='auto') , iris.data , iris.target , cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
import numpy as np
kernels = ['rbf' , 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval , C=cval , gamma='auto') , iris.data,iris.target,cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

# here we see that keeping kernel = linear and C=1 will give best score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

GridSearchCV


In [11]:
from sklearn.model_selection import GridSearchCV
clf  = GridSearchCV(svm.SVC(gamma='auto') , {
    'C':[1,10,20],
    'kernel' : ['rbf' , 'linear']
} , cv = 5 , return_train_score=False)

clf.fit(iris.data , iris.target)
clf.cv_results_

{'mean_fit_time': array([0.0013783 , 0.00106707, 0.0006248 , 0.00126619, 0.00118475,
        0.00040202]),
 'std_fit_time': array([4.38517117e-04, 3.41022254e-05, 7.65657109e-04, 7.80788740e-04,
        7.33093755e-04, 4.92374957e-04]),
 'mean_score_time': array([0.00085683, 0.0002059 , 0.00094557, 0.0005815 , 0.00122099,
        0.00059829]),
 'std_score_time': array([0.00073627, 0.0004118 , 0.00093215, 0.00055281, 0.00052413,
        0.00048853]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [12]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C   
0       0.001378      0.000439         0.000857        0.000736       1  \
1       0.001067      0.000034         0.000206        0.000412       1   
2       0.000625      0.000766         0.000946        0.000932      10   
3       0.001266      0.000781         0.000582        0.000553      10   
4       0.001185      0.000733         0.001221        0.000524      20   
5       0.000402      0.000492         0.000598        0.000489      20   

  param_kernel                         params  split0_test_score   
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667  \
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score   
0                1.0           0.966667           0.966667                1.0  \
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [13]:
df[['param_C' , 'param_kernel' , 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [14]:
clf.best_score_

0.9800000000000001

In [15]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [16]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel' : ['rbf' , 'linear']
} , 
cv = 5,
return_train_score=False,
n_iter=2
)
rs.fit(iris.data , iris.target)
pd.DataFrame(rs.cv_results_)[['param_C' , 'param_kernel' , 'mean_test_score']]


param_C param_kernel  mean_test_score
0      20       linear         0.966667
1      20          rbf         0.966667

In [17]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [18]:
model_params = {
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf' , 'linear']
        }
    },
    'random_forest'  : {
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1,5,10]
        }
    },
    'logistic_regression':{
        'model' : LogisticRegression(solver='liblinear' , multi_class='auto'),
        'params' : {
            'C' : [1,5,10]
        }
    }
}

In [19]:
scores = []

for model_name , mp in model_params.items():
    clf = GridSearchCV(mp['model'] , mp['params'] , cv=5 , return_train_score=False)
    clf.fit(iris.data , iris.target)
    scores.append({
        'model ' : model_name,
        'best_score': clf.best_score_,
        'best_params' : clf.best_params_,
    })

In [21]:
df = pd.DataFrame(scores,columns=['model' , 'best_score' , 'best_params'])
df

model  best_score                best_params
0    NaN    0.980000  {'C': 1, 'kernel': 'rbf'}
1    NaN    0.966667       {'n_estimators': 10}
2    NaN    0.966667                   {'C': 5}