In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits  = load_digits()

In [27]:
from sklearn.model_selection import train_test_split
X = digits.data
y = digits.target

In [28]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3)

In [29]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\siddh\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
lr.score(X_test,y_test)

0.9518518518518518

In [31]:
svm = SVC()
svm.fit(X_train,y_train)

SVC()

In [32]:
svm.score(X_test,y_test)

0.9777777777777777

In [33]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [34]:
rf.score(X_test,y_test)

0.9592592592592593

In [35]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [36]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [37]:
def get_score(model , X_train , X_test , y_train , y_test):
    model.fit(X_train,y_train)
    return model.score(X_test , y_test)

In [38]:
from sklearn.model_selection import StratifiedGroupKFold
folds = StratifiedGroupKFold(n_splits=3)

In [39]:
scores_l = []
scores_svm = []
scored_rf = []
for train_index , test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index] , digits.target[train_index] , digits.target[test_index]
    scores_l.append((get_score(LogisticRegression() , X_train , X_test , y_train , y_test)))
    scores_svm.append((get_score(SVC() , X_train , X_test , y_train , y_test)))
    scored_rf.append((get_score(RandomForestClassifier() , X_train , X_test , y_train , y_test)))

C:\Users\siddh\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\siddh\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mo

In [40]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [41]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [42]:
scored_rf

[0.9432387312186978, 0.9532554257095158, 0.9232053422370617]

In [43]:
from sklearn.model_selection import cross_val_score


In [44]:
cross_val_score(LogisticRegression() , digits.data , digits.target)

C:\Users\siddh\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\siddh\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mo

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [45]:
cross_val_score(SVC() , digits.data , digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [46]:
cross_val_score(RandomForestClassifier() , digits.data , digits.target)

array([0.94166667, 0.90555556, 0.95543175, 0.96657382, 0.91086351])